<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.17.1" />
    <PackageVersion Include="Azure.Security.KeyVault.Certificates" Version="4.8.0" />
    <PackageVersion Include="Azure.Security.KeyVault.Keys" Version="4.8.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta5.25306.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageVersion Include="System.IO.Packaging" Version="10.0.2" />
    <PackageVersion Include="NuGet.Packaging" Version="6.14.0" />
  </ItemGroup>
</Project>
